### ISSUE TITLE
Missing variant of Apache V2

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/fabric8-analytics-license-analysis#123]
We are missing this variant of Apache V2, so even though the license is known in the license graph, it is reported as unknown.
`Apache Software License v2.0`
![screenshot from 2018-08-23 14-22-05](https://user-images.githubusercontent.com/7047079/44515356-fac60780-a6df-11e8-9ae4-5f9df9ed0b76.png)

**Comment by sunilk747** [comment]
This PR- https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/125 takes care of this missing license. Closing this issue.

**Comment by samuzzal-choudhury** [comment]
This issue was moved to openshiftio/openshift.io#4256
