### ISSUE TITLE
Add new License ISC

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/fabric8-analytics-license-analysis#124]
![screenshot from 2018-08-23 14-28-55](https://user-images.githubusercontent.com/7047079/44515707-e0d8f480-a6e0-11e8-82cc-e7d9fbe89e90.png)

**Comment by sara-02** [comment]
Found via repo: https://github.com/yarnpkg/yarn

**Comment by sunilk747** [comment]
This PR- https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/128 accommodate the new license i.e ISC.
