### ISSUE TITLE
Please update list of maintainers to contain list of active maintainers

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-license-analysis#185]
https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/blob/964d1a9face7968f1034b53e5f3e0e3e919cd9b7/MAINTAINERS#L1

**Comment by yzainee** [comment]
@tisnik https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/pull/217. 
Will close this issue once the PR is merged. Let me know if you have any concerns
