### ISSUE TITLE
Run unit tests in CI

### ISSUE THREAD

**Issue by jpopelka** [fabric8-analytics/fabric8-analytics-license-analysis#22]
If I see correctly the existing [unit tests](https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/tree/master/tests) are not executed in CI  - for example in [this run](https://ci.centos.org/job/devtools-fabric8-analytics-license-analysis-fabric8-analytics/10/console).

Am I correct @msrb ?

**Comment by sara-02** [comment]
@jpopelka with this file in place, I think we have the unit test in CI, don't we?
https://github.com/fabric8-analytics/fabric8-analytics-license-analysis/blob/master/cico_run_tests.sh
I guess we can close this issue :)

**Comment by msrb** [comment]
Yup, @tisnik QA dashboard confirms that: https://fabric8-analytics.github.io/dashboard/dashboard.html.

Thanks everyone who helped with this :+1:  feel free to close.
